import type { DocumentDefinition } from '../../domain/types';

export const documents = [
  {
    id: 'pilack_release_check',
    kind: 'pilack',
    title: 'Pilack / release-check',
    appLabel: 'Pilack',
    dockLabel: 'Pilack',
    appColorToken: '#6b4e9e',
    iconLabel: '◆',
    isPrologueOnly: true,
    lines: [
      {
        id: 'pilack_release_thread_heading',
        text: '#release-check / 決済v2 Go/No-Go',
        style: 'heading',
      },
      {
        id: 'pilack_pm_schedule',
        speakerId: 'pm_saeki',
        timestamp: '18:04',
        text: '明日、checkout_v2、請求書出力、customer_data_migrationをまとめて出す前提で会議します。',
      },
      {
        id: 'pilack_techlead_flaky',
        speakerId: 'techlead_kurose',
        timestamp: '18:06',
        text: 'CIは一部落ちていますが、前から不安定なテストです。',
      },
      {
        id: 'pilack_sales_deadline',
        speakerId: 'sales_kiritani',
        timestamp: '18:08',
        text: '顧客には今月中に出すと伝えています。',
      },
    ],
  },
  {
    id: 'pira_bug_418',
    kind: 'pira',
    title: 'BUG-418: legacy_plan=true の顧客で checkout_v2 が失敗する',
    appLabel: 'Pira',
    dockLabel: 'Pira',
    appColorToken: '#2f68e0',
    iconLabel: '▤',
    isPrologueOnly: false,
    lines: [
      {
        id: 'pira_bug_title',
        text: 'BUG-418: legacy_plan=true の顧客で checkout_v2 が失敗する',
        style: 'heading',
      },
      {
        id: 'pira_bug_meta',
        text: 'Priority: P2 / Status: Open',
        style: 'comment',
      },
      {
        id: 'pira_qa_repro_count',
        speakerId: 'qa_mimura',
        text: 'QA comment: stagingで3回再現。',
        style: 'comment',
      },
      {
        id: 'pira_tax_null_checkout_500',
        speakerId: 'qa_mimura',
        text: 'tax_category が null の場合に migration 後の checkout で 500',
        style: 'comment',
        evidenceId: 'jira_bug_418_repro',
      },
      {
        id: 'pira_techlead_cleanup',
        speakerId: 'techlead_kurose',
        text: 'Tech Lead comment: 既存データの揺れによるもの。リリース後のcleanupで対応可能。',
        style: 'comment',
      },
    ],
  },
  {
    id: 'pr_tax_category_comment',
    kind: 'pr',
    title: 'PR #7821 checkout_v2 migration review',
    appLabel: 'PR',
    dockLabel: 'PR',
    appColorToken: '#7a5ad0',
    iconLabel: '⑃',
    isPrologueOnly: false,
    lines: [
      {
        id: 'pr_heading',
        text: 'PR #7821 / checkout_v2 migration',
        style: 'heading',
      },
      {
        id: 'pr_changed_files',
        text: 'Changed files: checkout_v2_mapper.ts, customer_tax_category.ts',
        style: 'code',
      },
      {
        id: 'pr_legacy_tax_null_review',
        speakerId: 'qa_mimura',
        text: 'legacy customer の tax_category が null の場合、migration 後に参照エラーになりませんか？',
        style: 'comment',
        evidenceId: 'pr_tax_category_comment',
      },
      {
        id: 'pr_response_defer_cleanup',
        speakerId: 'techlead_kurose',
        text: 'cleanup taskで吸収できる想定です。リリース後にデータ補正を走らせます。',
        style: 'comment',
      },
    ],
  },
  {
    id: 'ci_checkout_v2_failure',
    kind: 'ci',
    title: 'CI / CheckoutV2MigrationSpec',
    appLabel: 'CI',
    dockLabel: 'CI',
    appColorToken: '#2ba88c',
    iconLabel: '❯_',
    isPrologueOnly: false,
    lines: [
      {
        id: 'ci_heading',
        text: 'CI failure / CheckoutV2MigrationSpec',
        style: 'heading',
      },
      {
        id: 'ci_case_legacy_tax_null',
        text: 'legacy_plan=true / tax_category=null / CheckoutV2MigrationSpec failed',
        style: 'log_error',
        evidenceId: 'ci_legacy_failure',
      },
      {
        id: 'ci_stack_trace',
        text: 'TypeError: cannot read property "rate" of null at buildCheckoutTaxLine',
        style: 'code',
      },
      {
        id: 'ci_retry_status',
        text: 'Retry 3/3 failed with same fixture condition.',
        style: 'log_warn',
      },
    ],
  },
  {
    id: 'staging_500_log',
    kind: 'staging',
    title: 'Staging / checkout_v2 500 log',
    appLabel: 'Staging',
    dockLabel: 'Staging',
    appColorToken: '#e8a13a',
    iconLabel: '▲',
    isPrologueOnly: false,
    lines: [
      {
        id: 'staging_heading',
        text: 'staging checkout_v2 errors',
        style: 'heading',
      },
      {
        id: 'staging_repeated_500_legacy_tax_null',
        text: '500が11件反復。全部 legacy_plan=true / tax_category=null。',
        style: 'log_error',
        evidenceId: 'staging_500_log',
      },
      {
        id: 'staging_sample_request',
        text: 'GET /checkout_v2/session legacy_plan=true customer_id=legacy_2048',
        style: 'code',
      },
      {
        id: 'staging_status_note',
        text: '新規プラン顧客のcheckout_v2では同一エラーなし。',
        style: 'normal',
      },
    ],
  },
  {
    id: 'customer_email_scope',
    kind: 'mail',
    title: 'Customer email / 今月中の必要範囲',
    appLabel: 'Mail',
    dockLabel: 'Mail',
    appColorToken: '#2f8fd0',
    iconLabel: '✉',
    isPrologueOnly: false,
    lines: [
      {
        id: 'mail_heading',
        text: 'From: customer-ops@example.test / Subject: 今月中の対応範囲',
        style: 'heading',
      },
      {
        id: 'mail_invoice_only_this_month',
        text: '今月中に必要なのは、請求書出力の新フォーマット対応です。新しい決済フローについては、来月初旬の展開でも問題ありません。',
        style: 'quote',
        evidenceId: 'customer_email_scope',
      },
      {
        id: 'mail_follow_up',
        text: '経理締め処理に間に合えば、段階展開で問題ありません。',
        style: 'quote',
      },
    ],
  },
  {
    id: 'rollback_procedure',
    kind: 'runbook',
    title: 'Rollback Procedure / payment_v2',
    appLabel: 'Rollback',
    dockLabel: 'Rollbk',
    appColorToken: '#5a6576',
    iconLabel: '↩',
    isPrologueOnly: false,
    lines: [
      {
        id: 'rollback_heading',
        text: 'Rollback Procedure / payment_v2',
        style: 'heading',
      },
      {
        id: 'rollback_checkout_flag',
        text: 'checkout_v2 UI: feature flag offで旧UIへ戻せる。',
      },
      {
        id: 'rollback_invoice_export',
        text: 'invoice export: formatter flag offで旧フォーマットへ戻せる。',
      },
      {
        id: 'rollback_migration_irreversible',
        text: 'customer_data_migration: 本番write後の完全ロールバック不可。手動修正が必要。',
        style: 'log_warn',
        evidenceId: 'rollback_procedure',
      },
    ],
  },
  {
    id: 'feature_flag_design',
    kind: 'feature_flag',
    title: 'Feature Flag Design / payment_v2',
    appLabel: 'Feature Flags',
    dockLabel: 'FFlag',
    appColorToken: '#2ba88c',
    iconLabel: '⚑',
    isPrologueOnly: false,
    lines: [
      {
        id: 'fflag_heading',
        text: 'Feature Flags / payment_v2 rollout',
        style: 'heading',
      },
      {
        id: 'fflag_independent_invoice_checkout',
        text: 'checkout UI と invoice export は個別制御可能。customer_data_migration は一度writeすると完全な自動rollbackは不可。',
        style: 'normal',
        evidenceId: 'feature_flag_design',
      },
      {
        id: 'fflag_invoice_export',
        text: 'invoice_export_v2: account allowlist + gradual rollout supported.',
        style: 'code',
      },
      {
        id: 'fflag_checkout_ui',
        text: 'checkout_ui_v2: reversible by flag.',
        style: 'code',
      },
    ],
  },
  {
    id: 'past_incident_report',
    kind: 'incident',
    title: '過去Go/No-Go議事録 / staging warning ignored',
    appLabel: '議事録',
    dockLabel: '議事録',
    appColorToken: '#c85e34',
    iconLabel: '◷',
    isPrologueOnly: false,
    lines: [
      {
        id: 'incident_heading',
        text: 'Go/No-Go議事録: staging warning ignored',
        style: 'heading',
      },
      {
        id: 'incident_flaky_staging_warning',
        text: '前回議事録: staging警告をflakyとして扱い、本番で一部顧客の請求処理が失敗した。ただし原因は今回と直接同一ではない。',
        style: 'log_warn',
        evidenceId: 'past_incident_report',
      },
      {
        id: 'incident_action_item',
        text: '議事録メモ: 同一条件で反復する警告は、リリース前に条件を分解して確認する。',
      },
    ],
  },
  {
    id: 'cpu_spike_log',
    kind: 'metrics',
    title: 'Metrics / staging CPU spike',
    appLabel: 'Metrics',
    dockLabel: 'CPU',
    appColorToken: '#5a6576',
    iconLabel: '▧',
    isPrologueOnly: false,
    lines: [
      {
        id: 'cpu_heading',
        text: 'Metrics / staging',
        style: 'heading',
      },
      {
        id: 'cpu_spike_load_test',
        text: 'staging環境で一時的なCPUスパイクあり。原因は別チームの負荷テスト。',
        style: 'log_warn',
        evidenceId: 'cpu_spike_log',
      },
      {
        id: 'cpu_spike_detail',
        text: '21:08 CPU usage reached 92% for 4 minutes. 21:09 load-test-worker from analytics-team started batch simulation.',
        style: 'code',
      },
      {
        id: 'cpu_checkout_note',
        text: '今回の checkout_v2 migration とは直接関係が薄い。',
      },
    ],
  },
] satisfies DocumentDefinition[];
